//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTickets.WinUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eTickets.WinUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Email already exists.
        /// </summary>
        public static string msgEmailExist {
            get {
                return ResourceManager.GetString("msgEmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Email needs to be in valid format &quot;xxx@xxx.xxx&quot;.
        /// </summary>
        public static string msgEmailFormat {
            get {
                return ResourceManager.GetString("msgEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string msgError {
            get {
                return ResourceManager.GetString("msgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorized, you need to be administrator..
        /// </summary>
        public static string msgFailedAuthorization {
            get {
                return ResourceManager.GetString("msgFailedAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username or password .
        /// </summary>
        public static string msgFailedLogin {
            get {
                return ResourceManager.GetString("msgFailedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorized .
        /// </summary>
        public static string msgForbbiden {
            get {
                return ResourceManager.GetString("msgForbbiden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Password and confirmation does not match.
        /// </summary>
        public static string msgPasswordMatch {
            get {
                return ResourceManager.GetString("msgPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Password is too weak, at least 6 characters.
        /// </summary>
        public static string msgPasswordWeak {
            get {
                return ResourceManager.GetString("msgPasswordWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully denied.
        /// </summary>
        public static string msgRequestDenied {
            get {
                return ResourceManager.GetString("msgRequestDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully reseted password.
        /// </summary>
        public static string msgSucccessPasswordReset {
            get {
                return ResourceManager.GetString("msgSucccessPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully approved ticket.
        /// </summary>
        public static string msgSuccesApproved {
            get {
                return ResourceManager.GetString("msgSuccesApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added new admin.
        /// </summary>
        public static string msgSuccessAdd {
            get {
                return ResourceManager.GetString("msgSuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added .
        /// </summary>
        public static string msgSuccessAddItem {
            get {
                return ResourceManager.GetString("msgSuccessAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully changed personal data.
        /// </summary>
        public static string msgSuccessEdit {
            get {
                return ResourceManager.GetString("msgSuccessEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Username already exists.
        /// </summary>
        public static string msgUsernameExist {
            get {
                return ResourceManager.GetString("msgUsernameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Username can contain only letters and numbers.
        /// </summary>
        public static string msgUsernameNotLetterOrDigit {
            get {
                return ResourceManager.GetString("msgUsernameNotLetterOrDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Required field.
        /// </summary>
        public static string msgValidation_ReqField {
            get {
                return ResourceManager.GetString("msgValidation_ReqField", resourceCulture);
            }
        }
    }
}
